apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: dittofeed
    repo: oci://ghcr.io/sdobrovolschi/helm-charts
    version: 0.3.3
    namespace: dittofeed
    valuesFile: settings.yaml
    additionalValuesFiles:
    - replicas.yaml
    - version.yaml
