apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: rudderstack
    repo: oci://ghcr.io/sdobrovolschi/helm-charts
    version: 0.7.0
    namespace: rudderstack
    valuesFile: settings.yaml
    additionalValuesFiles:
    - replicas.yaml
    - version.yaml
patches:
  - path: statefulset.yaml
