apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: temporal
    repo: https://go.temporal.io/helm-charts
    version: 0.73.1
    namespace: temporal
    valuesFile: settings.yaml
    additionalValuesFiles:
    - replicas.yaml
    - version.yaml
    - namespaces.yaml
