apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: opa-kube-mgmt
    repo: https://open-policy-agent.github.io/kube-mgmt/charts
    version: 9.3.0
    namespace: opa
    valuesFile: settings.yaml
    additionalValuesFiles:
    - replicas.yaml
    - version.yaml
